version: "2"
services:
  openwrt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openwrt_imx6ull
    volumes: 
      - .:/source
#    command: bash -c "cp -R /home/build/openwrt/bin/targets/imx6ull/cortexa7/ /home/build/bin/"
    command: bash -c "./compile.sh all"

